_helpers/storage: Adapt cassandra keyspace initialization
[1] was not enough as it failed in staging

Follow-up on [1] f925323ead9786142f0ca93a52e49247f6b577bf

Refs. swh/infra/sysadm-environment#5562

diff --git a/swh/templates/utils/backend-utils.yaml b/swh/templates/utils/backend-utils.yaml
--- a/swh/templates/utils/backend-utils.yaml
+++ b/swh/templates/utils/backend-utils.yaml
@@ -268,13 +268,85 @@ data:
       $extra_cmd \
       $BACKEND
 
+  extract-storage-cassandra-config.py: |
+    import os
+    from swh.core import config
+    from swh.storage.cassandra import create_keyspace
+    from yaml import safe_dump
+
+    # This script reads a potentially complex storage configuration file (read
+    # from the file targetted by SWH_CONFIG_FILENAME). Complex configuration
+    # file are for example "cls: pipeline" configuration (vs of first level
+    # "cls: cassandra"). Its purpose is to extract the bare cassandra
+    # configuration stored in the configuration and outputs it the standard
+    # output.
+
+    def get_cassandra_config(storage_config):
+        if storage_config["cls"] == 'cassandra' :
+            return storage_config
+
+        if storage_config["cls"] == 'pipeline':
+            cassandra_config = storage_config["steps"][-1]
+            if cassandra_config["cls"] != "cassandra":
+                raise ValueError(
+                    "Misconfigured pipeline, the last step must be the actual "
+                    "cassandra storage configuration."
+                )
+
+            return cassandra_config
+
+        raise ValueError(
+            "Misconfigured storage configuration. It must be either a <pipeline> "
+            "or a <cassandra> storage instance."
+        )
+
+    config_file = os.environ.get("SWH_CONFIG_FILENAME")
+    full_config = config.read(config_file)
+    storage_config = full_config["storage"]
+    cassandra_conf = get_cassandra_config(storage_config)
+    hosts = cassandra_conf.get("hosts")
+    if not hosts:
+        raise ValueError(
+            "Misconfigured cassandra configuration, "
+            "<hosts> key must be provided."
+        )
+
+    auth_provider = cassandra_conf.get("auth_provider")
+    if not auth_provider:
+        raise ValueError(
+            "Misconfigured cassandra configuration, "
+            "<auth_provider> key must be provided."
+        )
+
+    keyspace = cassandra_conf.get("keyspace")
+    if not keyspace:
+        raise ValueError(
+            "Misconfigured cassandra configuration, "
+            "<keyspace> key must be provided."
+        )
+
+    # Expected config for the `swh storage create-keyspace` subcommand
+    config = {
+      "storage": cassandra_conf
+    }
+
+    print(safe_dump(config))
+
   init-cassandra-keyspace.sh: |
     #!/usr/bin/env bash
 
     [ -z "${SWH_CONFIG_FILENAME}" ] && \
-      echo "<SWH_CONFIG_FILENAME> env variable must be set" && exit 1
+        echo "<SWH_CONFIG_FILENAME> env variable must be set" && exit 1
 
-    swh storage create-keyspace
+    CONFIG_CASSANDRA=/etc/swh/storage-cassandra-config.yaml
+
+    python /entrypoints/extract-storage-cassandra-config.py > \
+        ${CONFIG_CASSANDRA}
+
+    [ ! -f "${CONFIG_CASSANDRA}" ] && \
+        echo "Missing <${CONFIG_CASSANDRA}> file" && exit 1
+
+    swh storage --config-file=${CONFIG_CASSANDRA} create-keyspace
 
   extract-storage-postgresql-config-py: |
     import yaml
