Prepare indexer storage template
Refs. swh/infra/sysadm-environment#4780

diff --git a/swh/templates/utils/database-utils.yaml b/swh/templates/utils/database-utils.yaml
--- a/swh/templates/utils/database-utils.yaml
+++ b/swh/templates/utils/database-utils.yaml
@@ -85,3 +85,31 @@ data:
       echo "code and DB versions are different. Blocking the deployment"
       exit 1
     fi
+
+  check-indexer-storage-db-version.sh: |
+    #!/bin/bash
+
+    set -eu
+
+    TEMP_FILE=/tmp/db-version.txt
+
+    # checking the database status
+    swh db --config-file=/tmp/config.yml version indexer-storage | tee "${TEMP_FILE}"
+
+    CODE_VERSION=$(awk -F':' '/code/ {print $2}' ${TEMP_FILE})
+    DB_VERSION=$(awk -F':' '/^version/ {print $2}' ${TEMP_FILE})
+
+    if [ -e "${CODE_VERSION}" ]; then
+      echo "Unable to find the code version"
+      exit 1
+    fi
+
+    if [ -e "${DB_VERSION}" ]; then
+      echo "Unable to find the code version"
+      exit 1
+    fi
+
+    if [ "$DB_VERSION" -ne "$CODE_VERSION" ]; then
+      echo "code and DB versions are different. Blocking the deployment"
+      exit 1
+    fi
